[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python3.11 -m pip install --upgrade pip", "python3.11 -m pip install -r requirements.txt"]

[start]
cmd = "python3.11 -m uvicorn server:app --host 0.0.0.0 --port $PORT"
